#! /bin/bash


_isInstalled() {
    package="$1"
    check="$(yay -Qs --color always "${package}" | grep "local" | grep "${package} ")"

    if [ -n "${check}" ]; then
        echo 0
        return
    fi
    echo 1
    return
}

_install_packages() {
    toInstall=()

    for pkg; do
        if [[ $(_isInstalled $pkg) == 0 ]]; then
            echo "$pkg is already installed."
            continue
        fi

        toInstall+=($pkg)
    done

    if [[ ${toInstall[@]} == "" ]]; then
        echo "All packages are already installed."
        return
    fi

    printf "Packages not installed:\n%s\n" ${toInstall[@]}
    yay -S ${toInstall[@]} --noconfirm
}


setup_yay() {
    echo "Installing yay - Yet another Yaourt"
    package="git"
    check="$(pacman -Qs --color always $package | grep "local" | grep "$package ")"
    if [ -n $check ]; then
        sudo pacman -S $package --noconfirm
    fi

    package="yay"
    check="$(pacman -Qs --color always $package | grep "local" | grep "$package ")"
    if [ -n $check ]; then
        git clone https://aur.archlinux.org/yay.git ~/yay
        current_dir=$(pwd)
        cd ~/yay
        makepkg -si --noconfirm
        cd $current_dir
        rm -rf ~/yay
    fi
}

get_dotfiles() {
    echo "Collecting dotfiles"

    packages=("git")
    _install_packages ${packages[@]}

    if [ -d $HOME/.dotfiles ]; then
        cd $HOME/.dotfiles
        git pull
    else
        git clone https://github.com/f12markovic/dotfiles.git $HOME/.dotfiles
        git --git-dir=$HOME/.dotfiles/.git/ --work-tree=$HOME/ config status.showUntrackedFiles no
    fi
}

setup_i3() {
    echo "Setting i3-gaps"

    packages=("xorg" "curl" "i3-gaps" "i3blocks" "i3lock-color" "compton" \
              "alsa" "alsa-utils" "alsa-firmware" "alsa-lib" "alsa-oss" \
              "alsa-plugins" "pulseaudio" "pulseaudio-alsa" "pavucontrol" \
              "arandr" "srandrd" "oblogout" "lxappearance" "rofi" "nautilus" \
              "thunar" "feh" "rxvt-unicode" "light" "xorg-setxkbmap" \
              "xorg-xset" "xorg-xsetroot" "xautolock" "i3-battery-nagbar" \
              "i3-scrot" "checkupdates+aur" "ranger" "wmctrl" "highlight" \
              "volumeicon" "gnome-terminal" "rxvt-unicode")
    # _install_packages ${packages[@]}

    # cp ~/.dotfiles/.config/i3/config ~/.config/i3/
    # cp ~/.dotfiles/.config/i3/i3blocks.conf ~/.config/i3/
    # cp -r ~/.dotfiles/.config/i3/scripts ~/.config/i3/
    # cp ~/.dotfiles/.config/compton.conf ~/.config/compton.conf
    bash -c "$((curl -fsSL https://raw.githubusercontent.com/denysdovhan/gnome-terminal-one/master/one-dark.sh) | sed 's/gconftool/gconftool-2/g')"
    return

    cp ~/.dotfiles/.config/gtk-3.0/gtk.css ~/.config/gtk-3.0/gtk.css

    cp $HOME/.dotfiles/.Xresources $HOME/
    cp $HOME/.dotfiles/.extend.Xresources $HOME/

    cp -r .dotfiles/suckless ~/.config/
    ~/.config/suckless/suckup

    user_dir=$HOME
    sudo ln -s $user_dir/.config/oblogout.conf /etc/oblogout.conf
}

setup_zsh() {
    echo "Setting zsh"

    packages=("wget" "curl" "fzf" "glib2" "zsh" "zsh-syntax-highlighting")
    _install_packages ${packages[@]}

    echo "exit" | sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    chsh -s $(which zsh)

    current_dir=$(pwd)
    mkdir -p $HOME/.zsh
    cd $HOME/.zsh
    wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh
    mv git-completion.zsh _git
    cd $current_dir

    cp -r $HOME/.dotfiles/.config/zsh-custom-themes/ $HOME/.config/
    cp $HOME/.dotfiles/.zshrc $HOME/
}

setup_vim() {
    echo "Setting vim"

    packages=("neovim" "python" "python-neovim" "python-pynvim" "python2-pynvim"
              "wl-clipboard" "xsel" "xclip" "ctags" "hasktags" "jupyter" "clang"
              "cmake" "gdb" "gdb-common" "lldb" "python-flake8-debugger"
              "python2-flake8-debugger" "octave")
    _install_packages ${packages[@]}

    mkdir -p ~/.vim/bundle
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    cp -r ~/.dotfiles/.vim/scripts ~/.vim/
    cp ~/.dotfiles/.vimrc ~/.vimrc

    # neovim - vim
    mkdir -p ~/.config/nvim/
    ln -s ~/.vimrc ~/.config/nvim/init.vim

    mkdir -p ~/.local/share/nvim/
    ln -s ~/.vim ~/.local/share/nvim/site

    nvim +PluginInstall +qa
    ~/.vim/bundle/YouCompleteMe/install.py
    cd ~/.vim/bundle/vimproc.vim && make
    nvim +UpdateRemotePlugins +qa

    cp ~/.dotfiles/.vim/bundle/vim-vebugger/autoload/vebugger.vim ~/.vim/bundle/vim-vebugger/autoload/vebugger.vim
    cp ~/.dotfiles/.vim/bundle/vim-vebugger/autoload/vebugger.vim ~/.vim/bundle/vim-vebugger/autoload/vebugger/std.vim
    cp ~/.dotfiles/.vim/bundle/vim-vebugger/autoload/vebugger.vim ~/.vim/bundle/vim-vebugger/plugin/vebugger.vim
    cp -r ~/.dotfiles/.vim/bundle/vim-template ~/.vim/bundle/vim-template
    cp -r ~/.dotfiles/.vim/syntax ~/.vim/syntax
    cp -r ~/.dotfiles/.vim/plugin ~/.vim/plugin
}

setup_zathura() {
    echo "Setting zathura"
    packages=("zathura" "zathura-pdf-mupdf" "zathura-djvu" "zathura-ps")
    _install_packages ${packages[@]}
    cp -r ~/.dotfiles/.config/zathura ~/.config/
}

setup_su() {
    echo "Setting su"

    user_dir=$HOME
    sudo ln -s $user_dir/.bashrc /root/.bashrc
    sudo ln -s $user_dir/.zshrc /root/.zshrc
    sudo ln -s $user_dir/.oh-my-zsh /root/.oh-my-zsh
    sudo ln -s $user_dir/.config/zsh-custom-themes /root/.config/zsh-custom-themes
    sudo ln -s $user_dir/.vimrc /root/.vimrc
    sudo ln -s $user_dir/.vim /root/.vim
    sudo mkdir -p /root/.config/nvim/
    sudo ln -s $user_dir/.vimrc /root/.config/nvim/init.vim
    sudo mkdir -p /root/.local/share/nvim/
    sudo ln -s $user_dir/.vim /root/.local/share/nvim/site
}

setup_flake8() {
    echo "Setting flake8"

    packages=("flake8")
    _install_packages ${packages[@]}
    cp ~/.dotfiles/.config/flake8 ~/.config/
}

setup_ncmpcpp() {
    echo "Setting ncmpcpp"

    packages=("mpd" "ncmpcpp")
    _install_packages ${packages[@]}

    mkdir $HOME/.ncmpcpp/
    cp $HOME/.dotfiles/.ncmpcpp/config $HOME/.ncmpcpp/
}

setup_apps() {
    echo "Installing other apps"

    packages=("r" "pandoc" "pandoc-citeproc" "google-chrome" \
               "skypeforlinux-stable-bin")
    _install_packages ${packages[@]}
    sudo R -e "install.packages(\"rmarkdown\", repos = \"https://cloud.r-project.org/\")"
}

setup_fonts() {
    echo "Installingg fonts"

    adobe_fonts=$(pacman -Ssq adobe-source)
    packages=("ttf-ubuntu-font-family" "otf-font-awesome"
              "awesome-terminal-fonts" "python-fontawesome" $adobe_fonts)
    _install_packages ${packages[@]}
}

# get_dotfiles
# setup_yay
# setup_i3
setup_zsh
# setup_vim
# setup_zathura
# setup_su
# setup_flake8
# setup_ncmpcpp
# setup_apps
# setup_fonts
# setup_flake8
